version: "1.0.0"
database:
  host: localhost
  port: 3306
  name: testdb
  user: testuser
  password: testpswd
server:
  host: localhost
  port: 9999
  env: DEVELOP
logging:
  level: DEBUG
util:
  # should not list the real secret in the config file if this is a productive level project
  jwt_secret: 4pJIfEt5T8GRg+h57Bwao6sk/t8KfAEg5Q9Ch49ko4Q=
